{
  "name": "mbpp_388_highest_Power_of_2",
  "language": "php",
  "prompt": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n",
  "doctests": "keep",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_388_highest_Power_of_2.py",
  "prompt_terminology": "verbatim",
  "tests": "function candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
  "stop_tokens": [
    "\nfunction",
    "\n?>",
    "\n//",
    "\n#"
  ],
  "results": [
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result <= $n) {\n        $result *= 2;\n    }\n    return $result/2;\n}\n\necho highest_Power_of_2(10);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(100);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "64\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpopgk081d.php:19\nStack trace:\n#0 /tmp/tmpopgk081d.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpopgk081d.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpairvrp9z.php:20\nStack trace:\n#0 /tmp/tmpairvrp9z.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpairvrp9z.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(30);\necho \"\\n\";\necho highest_Power_of_2(40);\necho \"\\n\";\necho highest_Power_of_2(50);\necho \"\\n\";\necho highest_Power_of_2(60);\necho \"\\n\";\necho highest_Power_of_2(70);\necho \"\\n\";\necho highest_Power_of_2(80);\necho \"\\n\";\necho highest_Power_of_2(90);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(110);\necho \"\\n\";\necho highest_Power_of_2(120);\necho \"\\n\";\necho highest_Power_of_2(130);\necho \"\\n\";\necho highest_Power_of_2(140);\necho \"\\n\";\necho highest_Power_of_2(150);\necho \"\\n\";\necho highest_Power_of_2(160);\necho \"\\n\";\necho highest_Power_of_2(170);\necho \"\\n\";\necho highest_Power_of_2(180);\necho \"\\n\";\necho highest_Power_of_2(190);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(210);\necho \"\\n\";\necho highest_Power_of_2(220);\necho \"\\n\";\necho highest_Power_of_2(230);\necho \"\\n\";\necho highest_Power_of_2(240);\necho \"\\n\";\necho highest_Power_of_2(250);\necho \"\\n\";\necho highest_Power_of_2(260);\necho \"\\n\";\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "8\n16\n16\n32\n32\n32\n64\n64\n64\n64\n64\n64\n128\n128\n128\n128\n128\n128\n128\n128\n128\n128\n128\n128\n128\n256\n",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfc7v8cq6.php:19\nStack trace:\n#0 /tmp/tmpfc7v8cq6.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpfc7v8cq6.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while(pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i-1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpminy5w11.php:18\nStack trace:\n#0 /tmp/tmpminy5w11.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpminy5w11.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(30);\necho \"\\n\";\necho highest_Power_of_2(40);\necho \"\\n\";\necho highest_Power_of_2(50);\necho \"\\n\";\necho highest_Power_of_2(60);\necho \"\\n\";\necho highest_Power_of_2(70);\necho \"\\n\";\necho highest_Power_of_2(80);\necho \"\\n\";\necho highest_Power_of_2(90);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(110);\necho \"\\n\";\necho highest_Power_of_2(120);\necho \"\\n\";\necho highest_Power_of_2(130);\necho \"\\n\";\necho highest_Power_of_2(140);\necho \"\\n\";\necho highest_Power_of_2(150);\necho \"\\n\";\necho highest_Power_of_2(160);\necho \"\\n\";\necho highest_Power_of_2(170);\necho \"\\n\";\necho highest_Power_of_2(180);\necho \"\\n\";\necho highest_Power_of_2(190);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(210);\necho \"\\n\";\necho highest_Power_of_2(220);\necho \"\\n\";\necho highest_Power_of_2(230);\necho \"\\n\";\necho highest_Power_of_2(240);\necho \"\\n\";\necho highest_Power_of_2(250);\necho \"\\n\";\necho highest_Power_of_2(260);\necho \"\\n\";\necho highest_Power_of_2(270);\necho \"\\n\";\necho highest_Power_of_2(280);\necho\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected identifier \"candidate\", expecting \"(\" in /tmp/tmpjz8zsvxt.php on line 67\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsmqjv74s.php:19\nStack trace:\n#0 /tmp/tmpsmqjv74s.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpsmqjv74s.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp1ia2h3bn.php:18\nStack trace:\n#0 /tmp/tmp1ia2h3bn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp1ia2h3bn.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p = $p * 2;\n    }\n    return $p / 2;\n}\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(30);\necho \"\\n\";\necho highest_Power_of_2(40);\necho \"\\n\";\necho highest_Power_of_2(50);\necho \"\\n\";\necho highest_Power_of_2(60);\necho \"\\n\";\necho highest_Power_of_2(70);\necho \"\\n\";\necho highest_Power_of_2(80);\necho \"\\n\";\necho highest_Power_of_2(90);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(110);\necho \"\\n\";\necho highest_Power_of_2(120);\necho \"\\n\";\necho highest_Power_of_2(130);\necho \"\\n\";\necho highest_Power_of_2(140);\necho \"\\n\";\necho highest_Power_of_2(150);\necho \"\\n\";\necho highest_Power_of_2(160);\necho \"\\n\";\necho highest_Power_of_2(170);\necho \"\\n\";\necho highest_Power_of_2(180);\necho \"\\n\";\necho highest_Power_of_2(190);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(210);\necho \"\\n\";\necho highest_Power_of_2(220);\necho \"\\n\";\necho highest_Power_of_2(230);\necho \"\\n\";\necho highest_Power_of_2(240);\necho \"\\n\";\necho highest_Power_of_2(250);\necho \"\\n\";\necho highest_Power_of_2(260);\necho \"\\n\";\necho highest_Power_of_2(270);\necho \"\\n\";\necho highest_Power_of_2(280);\necho \"\\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected identifier \"Test\", expecting \",\" or \";\" in /tmp/tmpnhqxx9sz.php on line 72\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result <= $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n  $i = 1;\n  while ($i < $n) {\n    $i *= 2;\n  }\n  return $i / 2;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpspst2ecq.php:18\nStack trace:\n#0 /tmp/tmpspst2ecq.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpspst2ecq.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbcn6isou.php:16\nStack trace:\n#0 /tmp/tmpbcn6isou.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpbcn6isou.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpskp13qpi.php:20\nStack trace:\n#0 /tmp/tmpskp13qpi.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpskp13qpi.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while(pow(2,$i) <= $n) {\n        $i++;\n    }\n    return pow(2,$i-1);\n}\n\necho highest_Power_of_2(100);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "64",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpafgpmxbr.php:19\nStack trace:\n#0 /tmp/tmpafgpmxbr.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpafgpmxbr.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $power = 0;\n    while ($n > 1) {\n        $n /= 2;\n        $power++;\n    }\n    return pow(2, $power);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpz3m9rbvn.php:19\nStack trace:\n#0 /tmp/tmpz3m9rbvn.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpz3m9rbvn.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcmngaa6w.php:18\nStack trace:\n#0 /tmp/tmpcmngaa6w.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpcmngaa6w.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9s030uer.php:20\nStack trace:\n#0 /tmp/tmp9s030uer.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp9s030uer.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p = $p + 1;\n    }\n    return pow(2, $p);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfavv3eop.php:19\nStack trace:\n#0 /tmp/tmpfavv3eop.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpfavv3eop.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpopp7zpkq.php:17\nStack trace:\n#0 /tmp/tmpopp7zpkq.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpopp7zpkq.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p++;\n    }\n    return pow(2, $p);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpk8qw1ipl.php:19\nStack trace:\n#0 /tmp/tmpk8qw1ipl.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpk8qw1ipl.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptcfz91hh.php:19\nStack trace:\n#0 /tmp/tmptcfz91hh.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptcfz91hh.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqelactet.php:17\nStack trace:\n#0 /tmp/tmpqelactet.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpqelactet.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p++;\n    }\n    return pow(2, $p);\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6luiui4v.php:17\nStack trace:\n#0 /tmp/tmp6luiui4v.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6luiui4v.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result < $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfqqizonx.php:19\nStack trace:\n#0 /tmp/tmpfqqizonx.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpfqqizonx.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result <= $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptcfz91hh.php:19\nStack trace:\n#0 /tmp/tmptcfz91hh.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptcfz91hh.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbtg60nu8.php:18\nStack trace:\n#0 /tmp/tmpbtg60nu8.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpbtg60nu8.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpskp13qpi.php:20\nStack trace:\n#0 /tmp/tmpskp13qpi.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpskp13qpi.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp1ia2h3bn.php:18\nStack trace:\n#0 /tmp/tmp1ia2h3bn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp1ia2h3bn.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqelactet.php:17\nStack trace:\n#0 /tmp/tmpqelactet.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpqelactet.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $n = intval($n);\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i-1);\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbcn6isou.php:16\nStack trace:\n#0 /tmp/tmpbcn6isou.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpbcn6isou.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpopp7zpkq.php:17\nStack trace:\n#0 /tmp/tmpopp7zpkq.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpopp7zpkq.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9s030uer.php:20\nStack trace:\n#0 /tmp/tmp9s030uer.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp9s030uer.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpskp13qpi.php:20\nStack trace:\n#0 /tmp/tmpskp13qpi.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpskp13qpi.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptcfz91hh.php:19\nStack trace:\n#0 /tmp/tmptcfz91hh.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptcfz91hh.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp1ia2h3bn.php:18\nStack trace:\n#0 /tmp/tmp1ia2h3bn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp1ia2h3bn.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p = $p + 1;\n    }\n    return pow(2, $p);\n}\n\necho highest_Power_of_2(8);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp15ui1ubg.php:18\nStack trace:\n#0 /tmp/tmp15ui1ubg.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp15ui1ubg.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcmngaa6w.php:18\nStack trace:\n#0 /tmp/tmpcmngaa6w.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpcmngaa6w.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n /= 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(64);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "64\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvy1it5f8.php:19\nStack trace:\n#0 /tmp/tmpvy1it5f8.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpvy1it5f8.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result <= $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $power = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $power++;\n    }\n    return pow(2, $power);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpgjnenibt.php:18\nStack trace:\n#0 /tmp/tmpgjnenibt.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpgjnenibt.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpq1li7s8s.php:21\nStack trace:\n#0 /tmp/tmpq1li7s8s.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpq1li7s8s.php on line 21\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(8);\necho \"\\n\";\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(15);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(25);\necho \"\\n\";\necho highest_Power_of_2(32);\necho \"\\n\";\necho highest_Power_of_2(63);\necho \"\\n\";\necho highest_Power_of_2(64);\necho \"\\n\";\necho highest_Power_of_2(65);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(127);\necho \"\\n\";\necho highest_Power_of_2(128);\necho \"\\n\";\necho highest_Power_of_2(129);\necho \"\\n\";\necho highest_Power_of_2(1000);\necho \"\\n\";\necho highest_Power_of_2(1023);\necho \"\\n\";\necho highest_Power_of_2(1024);\necho \"\\n\";\necho highest_Power_of_2(1025);\necho \"\\n\";\necho highest_Power_of_2(1026);\necho \"\\n\";\necho highest_Power_of_2(1028);\necho \"\\n\";\necho highest_Power_of_2(1030);\necho \"\\n\";\necho highest_Power_of_2(1031);\necho \"\\n\";\necho highest_Power_of_2(1032);\necho \"\\n\";\necho highest_Power_of_2(1033);\necho \"\\n\";\necho highest_Power_of_2(1034);\necho \"\\n\";\necho highest_Power_of_2(1035);\necho \"\\n\";\necho highest_Power_of_2(1036);\necho \"\\n\";\necho highest_Power_of_2(1037\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \")\" in /tmp/tmp4bpl0cc_.php on line 65\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while(pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\necho highest_Power_of_2(10);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpipsx2zm1.php:19\nStack trace:\n#0 /tmp/tmpipsx2zm1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpipsx2zm1.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $res = 1;\n    while ($res <= $n) {\n        $res *= 2;\n    }\n    return $res / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > pow(2, $i)) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqfo1finy.php:19\nStack trace:\n#0 /tmp/tmpqfo1finy.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpqfo1finy.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbtg60nu8.php:18\nStack trace:\n#0 /tmp/tmpbtg60nu8.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpbtg60nu8.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpairvrp9z.php:20\nStack trace:\n#0 /tmp/tmpairvrp9z.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpairvrp9z.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while(pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i-1);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > pow(2, $i)) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqfo1finy.php:19\nStack trace:\n#0 /tmp/tmpqfo1finy.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpqfo1finy.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpa3m2umkw.php:17\nStack trace:\n#0 /tmp/tmpa3m2umkw.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpa3m2umkw.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9s030uer.php:20\nStack trace:\n#0 /tmp/tmp9s030uer.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp9s030uer.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p = $p * 2;\n    }\n    return $p / 2;\n}\n\n$n = 100;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "64\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp96kft4h9.php:20\nStack trace:\n#0 /tmp/tmp96kft4h9.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp96kft4h9.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(100);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "64\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpopgk081d.php:19\nStack trace:\n#0 /tmp/tmpopgk081d.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpopgk081d.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p += 1;\n    }\n    return pow(2, $p);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2nn3kwyt.php:19\nStack trace:\n#0 /tmp/tmp2nn3kwyt.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp2nn3kwyt.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i;\n}\n\necho highest_Power_of_2(10);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3lj7ihz8.php:18\nStack trace:\n#0 /tmp/tmp3lj7ihz8.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp3lj7ihz8.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p = $p + 1;\n    }\n    return pow(2, $p);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfavv3eop.php:19\nStack trace:\n#0 /tmp/tmpfavv3eop.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpfavv3eop.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p = $p * 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqz_veqwy.php:20\nStack trace:\n#0 /tmp/tmpqz_veqwy.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqz_veqwy.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $res = 1;\n    while ($res <= $n) {\n        $res *= 2;\n    }\n    return $res / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpipsx2zm1.php:19\nStack trace:\n#0 /tmp/tmpipsx2zm1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpipsx2zm1.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp1ia2h3bn.php:18\nStack trace:\n#0 /tmp/tmp1ia2h3bn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp1ia2h3bn.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpminy5w11.php:18\nStack trace:\n#0 /tmp/tmpminy5w11.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpminy5w11.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpairvrp9z.php:20\nStack trace:\n#0 /tmp/tmpairvrp9z.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpairvrp9z.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpx6njcifs.php:18\nStack trace:\n#0 /tmp/tmpx6njcifs.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpx6njcifs.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(300);\necho \"\\n\";\necho highest_Power_of_2(400);\necho \"\\n\";\necho highest_Power_of_2(500);\necho \"\\n\";\necho highest_Power_of_2(600);\necho \"\\n\";\necho highest_Power_of_2(700);\necho \"\\n\";\necho highest_Power_of_2(800);\necho \"\\n\";\necho highest_Power_of_2(900);\necho \"\\n\";\necho highest_Power_of_2(1000);\necho \"\\n\";\necho highest_Power_of_2(1100);\necho \"\\n\";\necho highest_Power_of_2(1200);\necho \"\\n\";\necho highest_Power_of_2(1300);\necho \"\\n\";\necho highest_Power_of_2(1400);\necho \"\\n\";\necho highest_Power_of_2(1500);\necho \"\\n\";\necho highest_Power_of_2(1600);\necho \"\\n\";\necho highest_Power_of_2(1700);\necho \"\\n\";\necho highest_Power_of_2(1800);\necho \"\\n\";\necho highest_Power_of_2(1900);\necho \"\\n\";\necho highest_Power_of_2(2000);\necho \"\\n\";\necho highest_Power_of_2(2100);\necho \"\\n\";\necho highest_Power_of_2(2200);\necho \"\\n\";\necho highest_Power_of_2(2300);\necho \"\\n\";\necho highest_Power_of_2(2400);\necho \"\\n\";\necho highest_Power_of_2(2500);\necho \"\\n\";\necho highest_Power_of_\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \",\" or \";\" in /tmp/tmpvfa99bzb.php on line 66\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $power = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $power++;\n    }\n    return pow(2, $power);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpy732_gz3.php:19\nStack trace:\n#0 /tmp/tmpy732_gz3.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpy732_gz3.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoa6m_vfb.php:18\nStack trace:\n#0 /tmp/tmpoa6m_vfb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpoa6m_vfb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpminy5w11.php:18\nStack trace:\n#0 /tmp/tmpminy5w11.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpminy5w11.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    for ($i = 0; $i <= $n; $i++) {\n        $result = $result * 2;\n        if ($result > $n) {\n            return $result / 2;\n        }\n    }\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(40);\necho \"\\n\";\necho highest_Power_of_2(50);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(150);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(250);\necho \"\\n\";\necho highest_Power_of_2(300);\necho \"\\n\";\necho highest_Power_of_2(350);\necho \"\\n\";\necho highest_Power_of_2(400);\necho \"\\n\";\necho highest_Power_of_2(450);\necho \"\\n\";\necho highest_Power_of_2(500);\necho \"\\n\";\necho highest_Power_of_2(550);\necho \"\\n\";\necho highest_Power_of_2(600);\necho \"\\n\";\necho highest_Power_of_2(650);\necho \"\\n\";\necho highest_Power_of_2(700);\necho \"\\n\";\necho highest_Power_of_2(750);\necho \"\\n\";\necho highest_Power_of_2(800);\necho \"\\n\";\necho highest_Power_of_2(850);\necho \"\\n\";\necho highest_Power_of_2(900);\necho \"\\n\";\necho highest_Power_of_2(950);\necho \"\\n\";\necho highest_Power_of_2(1000);\necho \"\\n\";\necho highest_Power_of_2(1050);\necho \"\\n\";\necho highest_Power_of_2(1100);\necho \"\\n\";\necho highest_Power_of_2(1150);\necho \"\\n\";\necho highest_Power_\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \",\" or \";\" in /tmp/tmppw9mgbl0.php on line 66\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(256);\necho \"\\n\";\necho highest_Power_of_2(1);\necho \"\\n\";\necho highest_Power_of_2(0);\necho \"\\n\";\necho highest_Power_of_2(2);\necho \"\\n\";\necho highest_Power_of_2(3);\necho \"\\n\";\necho highest_Power_of_2(4);\necho \"\\n\";\necho highest_Power_of_2(5);\necho \"\\n\";\necho highest_Power_of_2(6);\necho \"\\n\";\necho highest_Power_of_2(7);\necho \"\\n\";\necho highest_Power_of_2(8);\necho \"\\n\";\necho highest_Power_of_2(9);\necho \"\\n\";\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(11);\necho \"\\n\";\necho highest_Power_of_2(12);\necho \"\\n\";\necho highest_Power_of_2(13);\necho \"\\n\";\necho highest_Power_of_2(14);\necho \"\\n\";\necho highest_Power_of_2(15);\necho \"\\n\";\necho highest_Power_of_2(16);\necho \"\\n\";\necho highest_Power_of_2(17);\necho \"\\n\";\necho highest_Power_of_2(18);\necho \"\\n\";\necho highest_Power_of_2(19);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(21);\necho \"\\n\";\necho highest_Power_of_2(22);\necho \"\\n\";\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\n64\n256\n1\n0\n2\n2\n4\n4\n4\n4\n8\n8\n8\n8\n8\n8\n8\n8\n16\n16\n16\n16\n16\n16\n16\n",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8u2uycjm.php:18\nStack trace:\n#0 /tmp/tmp8u2uycjm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp8u2uycjm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptcfz91hh.php:19\nStack trace:\n#0 /tmp/tmptcfz91hh.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptcfz91hh.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\necho highest_Power_of_2(5);\necho \"\\n\";\necho highest_Power_of_2(16);\necho \"\\n\";\necho highest_Power_of_2(24);\necho \"\\n\";\necho highest_Power_of_2(32);\necho \"\\n\";\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "4\n16\n16\n32\n",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp1ia2h3bn.php:18\nStack trace:\n#0 /tmp/tmp1ia2h3bn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp1ia2h3bn.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(30);\necho \"\\n\";\necho highest_Power_of_2(40);\necho \"\\n\";\necho highest_Power_of_2(50);\necho \"\\n\";\necho highest_Power_of_2(60);\necho \"\\n\";\necho highest_Power_of_2(70);\necho \"\\n\";\necho highest_Power_of_2(80);\necho \"\\n\";\necho highest_Power_of_2(90);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(110);\necho \"\\n\";\necho highest_Power_of_2(120);\necho \"\\n\";\necho highest_Power_of_2(130);\necho \"\\n\";\necho highest_Power_of_2(140);\necho \"\\n\";\necho highest_Power_of_2(150);\necho \"\\n\";\necho highest_Power_of_2(160);\necho \"\\n\";\necho highest_Power_of_2(170);\necho \"\\n\";\necho highest_Power_of_2(180);\necho \"\\n\";\necho highest_Power_of_2(190);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(210);\necho \"\\n\";\necho highest_Power_of_2(220);\necho \"\\n\";\necho highest_Power_of_2(230);\necho \"\\n\";\necho highest_Power_of_2(240);\necho \"\\n\";\necho highest_Power_of_2(250);\necho \"\\n\";\necho highest_Power_of_2(260);\necho \"\\n\";\necho highest_Power_of_2(270);\necho \"\\n\";\necho highest_Power_\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \",\" or \";\" in /tmp/tmpga7nboeb.php on line 67\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i-1);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result < $n) {\n        $result = $result * 2;\n    }\n    return $result / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjpe4oflj.php:20\nStack trace:\n#0 /tmp/tmpjpe4oflj.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpjpe4oflj.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpskp13qpi.php:20\nStack trace:\n#0 /tmp/tmpskp13qpi.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpskp13qpi.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(1000);\necho \"\\n\";\necho highest_Power_of_2(10000);\necho \"\\n\";\necho highest_Power_of_2(100000);\necho \"\\n\";\necho highest_Power_of_2(1000000);\necho \"\\n\";\necho highest_Power_of_2(10000000);\necho \"\\n\";\necho highest_Power_of_2(100000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \")\" in /tmp/tmpr16a2p22.php on line 62\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > pow(2, $i)) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp49w7lt1u.php:20\nStack trace:\n#0 /tmp/tmp49w7lt1u.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp49w7lt1u.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n  $i = 1;\n  while ($i < $n) {\n    $i *= 2;\n  }\n  return $i / 2;\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(1000);\necho \"\\n\";\necho highest_Power_of_2(10000);\necho \"\\n\";\necho highest_Power_of_2(100000);\necho \"\\n\";\necho highest_Power_of_2(1000000);\necho \"\\n\";\necho highest_Power_of_2(10000000);\necho \"\\n\";\necho highest_Power_of_2(100000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(100000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(1000000000000000000000000);\necho \"\\n\";\necho highest_Power_of_2(10000000000000000\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \")\" in /tmp/tmpxfnspcp0.php on line 62\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 0) {\n        $n = $n >> 1;\n        $p = $p + 1;\n    }\n    return 1 << ($p - 1);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpx6njcifs.php:18\nStack trace:\n#0 /tmp/tmpx6njcifs.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpx6njcifs.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpx6njcifs.php:18\nStack trace:\n#0 /tmp/tmpx6njcifs.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpx6njcifs.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $p = $p + 1;\n    }\n    return pow(2, $p);\n}\n\n$n = 100;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "128\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbj1lse0m.php:19\nStack trace:\n#0 /tmp/tmpbj1lse0m.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpbj1lse0m.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result < $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjplln81o.php:18\nStack trace:\n#0 /tmp/tmpjplln81o.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjplln81o.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result <= $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpa3m2umkw.php:17\nStack trace:\n#0 /tmp/tmpa3m2umkw.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpa3m2umkw.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $n = $n | ($n >> 1);\n    $n = $n | ($n >> 2);\n    $n = $n | ($n >> 4);\n    $n = $n | ($n >> 8);\n    $n = $n | ($n >> 16);\n    return ($n + 1) >> 1;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $n = $n | ($n >> 1);\n    $n = $n | ($n >> 2);\n    $n = $n | ($n >> 4);\n    $n = $n | ($n >> 8);\n    $n = $n | ($n >> 16);\n    return $n - ($n >> 1);\n}\n\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(256);\necho \"\\n\";\necho highest_Power_of_2(300);\necho \"\\n\";\necho highest_Power_of_2(1024);\necho \"\\n\";\necho highest_Power_of_2(1023);\necho \"\\n\";\necho highest_Power_of_2(1024);\necho \"\\n\";\necho highest_Power_of_2(1025);\necho \"\\n\";\necho highest_Power_of_2(1);\necho \"\\n\";\necho highest_Power_of_2(0);\necho \"\\n\";\necho highest_Power_of_2(-1);\necho \"\\n\";\necho highest_Power_of_2(-2);\necho \"\\n\";\necho highest_Power_of_2(-3);\necho \"\\n\";\necho highest_Power_of_2(-4);\necho \"\\n\";\necho highest_Power_of_2(-5);\necho \"\\n\";\necho highest_Power_of_2(-6);\necho \"\\n\";\necho highest_Power_of_2(-7);\necho \"\\n\";\necho highest_Power_of_2(-8);\necho \"\\n\";\necho highest_Power_of_2(-9);\necho \"\\n\";\necho highest_Power_of_2(-10);\necho \"\\n\";\necho highest_Power_of_2(-11);\necho \"\\n\";\necho highest_Power_of_2(-12);\necho \"\\n\";\necho highest_Power_of_2(-13);\necho \"\\n\";\necho highest_Power_of_2(-14);\necho \"\\n\";\necho highest_Power_of_2(-15);\necho \"\\n\";\necho highest_Power_\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \",\" or \";\" in /tmp/tmpfncn_u3s.php on line 63\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result < $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfqqizonx.php:19\nStack trace:\n#0 /tmp/tmpfqqizonx.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpfqqizonx.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp51shj_gw.php:16\nStack trace:\n#0 /tmp/tmp51shj_gw.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp51shj_gw.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbcn6isou.php:16\nStack trace:\n#0 /tmp/tmpbcn6isou.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpbcn6isou.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpr_hgj6su.php:17\nStack trace:\n#0 /tmp/tmpr_hgj6su.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpr_hgj6su.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = 100;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "64\nFatal error: Uncaught Exception: Test failed! in /tmp/tmphxmojrcx.php:20\nStack trace:\n#0 /tmp/tmphxmojrcx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmphxmojrcx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 0) {\n        $p++;\n        $n = $n >> 1;\n    }\n    return pow(2, $p - 1);\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > pow(2, $i)) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp49w7lt1u.php:20\nStack trace:\n#0 /tmp/tmp49w7lt1u.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp49w7lt1u.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $res = 0;\n    for ($i = $n; $i >= 1; $i--) {\n        $res = $i;\n        if ($i % 2 != 0)\n            break;\n    }\n    return $res;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "9\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqo7t9y4f.php:19\nStack trace:\n#0 /tmp/tmpqo7t9y4f.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpqo7t9y4f.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\n$n = 10;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpminy5w11.php:18\nStack trace:\n#0 /tmp/tmpminy5w11.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpminy5w11.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptcfz91hh.php:19\nStack trace:\n#0 /tmp/tmptcfz91hh.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptcfz91hh.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\necho highest_Power_of_2(5);\necho \"\\n\";\necho highest_Power_of_2(16);\necho \"\\n\";\necho highest_Power_of_2(24);\necho \"\\n\";\necho highest_Power_of_2(32);\necho \"\\n\";\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "4\n16\n16\n32\n",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if (pow(2, $i) <= $n) {\n            $result = pow(2, $i);\n        }\n    }\n    return $result;\n}\n\necho highest_Power_of_2(10);\n\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p <= $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsbye_738.php:20\nStack trace:\n#0 /tmp/tmpsbye_738.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsbye_738.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 0;\n    while ($n > 1) {\n        $n = $n >> 1;\n        $p++;\n    }\n    return 1 << $p;\n}\n\necho highest_Power_of_2(8);\necho \"\\n\";\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(1024);\necho \"\\n\";\necho highest_Power_of_2(1023);\necho \"\\n\";\necho highest_Power_of_2(1024);\necho \"\\n\";\necho highest_Power_of_2(1025);\necho \"\\n\";\necho highest_Power_of_2(1);\necho \"\\n\";\necho highest_Power_of_2(0);\necho \"\\n\";\necho highest_Power_of_2(-1);\necho \"\\n\";\necho highest_Power_of_2(-2);\necho \"\\n\";\necho highest_Power_of_2(-3);\necho \"\\n\";\necho highest_Power_of_2(-4);\necho \"\\n\";\necho highest_Power_of_2(-5);\necho \"\\n\";\necho highest_Power_of_2(-6);\necho \"\\n\";\necho highest_Power_of_2(-7);\necho \"\\n\";\necho highest_Power_of_2(-8);\necho \"\\n\";\necho highest_Power_of_2(-9);\necho \"\\n\";\necho highest_Power_of_2(-10);\necho \"\\n\";\necho highest_Power_of_2(-11);\necho \"\\n\";\necho highest_Power_of_2(-12);\necho \"\\n\";\necho highest_Power_of_2(-13);\necho \"\\n\";\necho highest_Power_of_2(-14);\necho \"\\n\";\necho highest_Power_of_2(-15);\necho \"\\n\";\necho highest_Power_of_2(-16);\necho \"\\n\";\necho highest_Power_of_2(-17);\necho \"\\n\";\necho highest_Power_of_2(-18);\necho \"\\n\";\necho highest_Power_\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \",\" or \";\" in /tmp/tmp_mi6t_4a.php on line 67\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result < $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\n$n = 100;\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "64\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5djmnkvw.php:20\nStack trace:\n#0 /tmp/tmp5djmnkvw.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5djmnkvw.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $p = 1;\n    while ($p < $n) {\n        $p *= 2;\n    }\n    return $p / 2;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpafgpmxbr.php:19\nStack trace:\n#0 /tmp/tmpafgpmxbr.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpafgpmxbr.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while (pow(2, $i) <= $n) {\n        $i++;\n    }\n    return pow(2, $i - 1);\n}\necho highest_Power_of_2(10);\necho \"\\n\";\necho highest_Power_of_2(20);\necho \"\\n\";\necho highest_Power_of_2(40);\necho \"\\n\";\necho highest_Power_of_2(100);\necho \"\\n\";\necho highest_Power_of_2(200);\necho \"\\n\";\necho highest_Power_of_2(400);\necho \"\\n\";\necho highest_Power_of_2(800);\necho \"\\n\";\necho highest_Power_of_2(1600);\necho \"\\n\";\necho highest_Power_of_2(3200);\necho \"\\n\";\necho highest_Power_of_2(6400);\necho \"\\n\";\necho highest_Power_of_2(12800);\necho \"\\n\";\necho highest_Power_of_2(25600);\necho \"\\n\";\necho highest_Power_of_2(51200);\necho \"\\n\";\necho highest_Power_of_2(102400);\necho \"\\n\";\necho highest_Power_of_2(204800);\necho \"\\n\";\necho highest_Power_of_2(409600);\necho \"\\n\";\necho highest_Power_of_2(819200);\necho \"\\n\";\necho highest_Power_of_2(1638400);\necho \"\\n\";\necho highest_Power_of_2(3276800);\necho \"\\n\";\necho highest_Power_of_2(6553600);\necho \"\\n\";\necho highest_Power_of_2(13107200);\necho \"\\n\";\necho highest_Power_of_2(26214400);\necho \"\\n\";\necho highest_Power_of_2(52428800);\necho \"\\n\";\necho highest_Power_of_2(104857600);\necho \"\\n\";\necho highest_Power_of_2(209715200);\necho \"\\n\";\necho highest_Power_of_2(4\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "\nParse error: syntax error, unexpected token \"function\", expecting \")\" in /tmp/tmp6z73idcu.php on line 61\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i = $i * 2;\n    }\n    return $i;\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpopp7zpkq.php:17\nStack trace:\n#0 /tmp/tmpopp7zpkq.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpopp7zpkq.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result < $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsm05mp59.php:20\nStack trace:\n#0 /tmp/tmpsm05mp59.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpsm05mp59.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 1;\n    while ($i < $n) {\n        $i *= 2;\n    }\n    return $i / 2;\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "0.5\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp520yabzx.php:20\nStack trace:\n#0 /tmp/tmp520yabzx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp520yabzx.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while ($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\n$n = intval(fgets(STDIN));\necho highest_Power_of_2($n);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510383,
      "stdout": "1\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpzh8i8ege.php:19\nStack trace:\n#0 /tmp/tmpzh8i8ege.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpzh8i8ege.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $i = 0;\n    while($n > 1) {\n        $n = $n / 2;\n        $i++;\n    }\n    return pow(2, $i);\n}\n\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "16\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7a6yel8q.php:18\nStack trace:\n#0 /tmp/tmp7a6yel8q.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp7a6yel8q.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a python function to find the highest power of 2 that is less than or equal to n.\nfunction highest_Power_of_2($n) {\n    $result = 1;\n    while ($result <= $n) {\n        $result *= 2;\n    }\n    return $result / 2;\n}\necho highest_Power_of_2(10);\nfunction candidate(...$args) {\n    return highest_Power_of_2(...$args);\n}\n\nfunction test(): void {\n    if (candidate(10) !== 8) { throw new Exception(\"Test failed!\"); }\n    if (candidate(19) !== 16) { throw new Exception(\"Test failed!\"); }\n    if (candidate(32) !== 32) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123422,
      "stdout": "8",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    }
  ]
}