{
  "name": "mbpp_287_square_Sum",
  "language": "php",
  "prompt": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n",
  "doctests": "transform",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_287_square_Sum.py",
  "prompt_terminology": "reworded",
  "tests": "function candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
  "stop_tokens": [
    "\nfunction",
    "\n?>",
    "\n//",
    "\n#"
  ],
  "results": [
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps8jkht56.php:17\nStack trace:\n#0 /tmp/tmps8jkht56.php(22): test()\n#1 {main}\n  thrown in /tmp/tmps8jkht56.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvoq_tuve.php:16\nStack trace:\n#0 /tmp/tmpvoq_tuve.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpvoq_tuve.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\n$n = 4;\necho square_Sum($n);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps9642b4x.php:19\nStack trace:\n#0 /tmp/tmps9642b4x.php(24): test()\n#1 {main}\n  thrown in /tmp/tmps9642b4x.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum = $sum + $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyz7is9h0.php:18\nStack trace:\n#0 /tmp/tmpyz7is9h0.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyz7is9h0.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp21kymc9k.php:16\nStack trace:\n#0 /tmp/tmp21kymc9k.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp21kymc9k.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptv4chd3w.php:17\nStack trace:\n#0 /tmp/tmptv4chd3w.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptv4chd3w.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6v2xdkkv.php:16\nStack trace:\n#0 /tmp/tmp6v2xdkkv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp6v2xdkkv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n$n = 10;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "385\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6se_78p4.php:17\nStack trace:\n#0 /tmp/tmp6se_78p4.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp6se_78p4.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpriea2ue2.php:17\nStack trace:\n#0 /tmp/tmpriea2ue2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpriea2ue2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for ($i = 1; $i <= $n; $i++) {\n    if ($i % 2 == 0) {\n      $sum += $i * $i;\n    }\n  }\n  return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpayep28mp.php:19\nStack trace:\n#0 /tmp/tmpayep28mp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpayep28mp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpi7f5fgr9.php:16\nStack trace:\n#0 /tmp/tmpi7f5fgr9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpi7f5fgr9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n$n = 10;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmr8v20c3.php:19\nStack trace:\n#0 /tmp/tmpmr8v20c3.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpmr8v20c3.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpap1yexn_.php:18\nStack trace:\n#0 /tmp/tmpap1yexn_.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpap1yexn_.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i < $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "120\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8pfshfgd.php:17\nStack trace:\n#0 /tmp/tmp8pfshfgd.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp8pfshfgd.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\necho square_Sum(4);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfw08ofbg.php:17\nStack trace:\n#0 /tmp/tmpfw08ofbg.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpfw08ofbg.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpapqkkxt1.php:17\nStack trace:\n#0 /tmp/tmpapqkkxt1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpapqkkxt1.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqd_najyd.php:18\nStack trace:\n#0 /tmp/tmpqd_najyd.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqd_najyd.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\n$n = 10;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp21xbeo4x.php:20\nStack trace:\n#0 /tmp/tmp21xbeo4x.php(25): test()\n#1 {main}\n  thrown in /tmp/tmp21xbeo4x.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n$n = 5;\necho \"Sum of squares of first $n even natural numbers is \" . square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "Sum of squares of first 5 even natural numbers is 55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcsx4l6w2.php:17\nStack trace:\n#0 /tmp/tmpcsx4l6w2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpcsx4l6w2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=1; $i <= $n; $i++) { \n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpy2qbrhnm.php:17\nStack trace:\n#0 /tmp/tmpy2qbrhnm.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpy2qbrhnm.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i * 2, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6v2xdkkv.php:16\nStack trace:\n#0 /tmp/tmp6v2xdkkv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp6v2xdkkv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\n$n = 10;\necho \"Sum of squares of first $n even natural numbers is : \" . square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "Sum of squares of first 10 even natural numbers is : 385\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpm_97i7f5.php:18\nStack trace:\n#0 /tmp/tmpm_97i7f5.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpm_97i7f5.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpahb3amq2.php:17\nStack trace:\n#0 /tmp/tmpahb3amq2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpahb3amq2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvu_om23_.php:18\nStack trace:\n#0 /tmp/tmpvu_om23_.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpvu_om23_.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\n$n = 5;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpp5mrl_2r.php:18\nStack trace:\n#0 /tmp/tmpp5mrl_2r.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpp5mrl_2r.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpapqkkxt1.php:17\nStack trace:\n#0 /tmp/tmpapqkkxt1.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpapqkkxt1.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n\t$sum = 0;\n\tfor ($i=1; $i <= $n; $i++) { \n\t\t$sum += $i*$i;\n\t}\n\treturn $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8g1t9w02.php:16\nStack trace:\n#0 /tmp/tmp8g1t9w02.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp8g1t9w02.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6v2xdkkv.php:16\nStack trace:\n#0 /tmp/tmp6v2xdkkv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp6v2xdkkv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\nprint_r(square_Sum(5));\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfr44jj2_.php:16\nStack trace:\n#0 /tmp/tmpfr44jj2_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpfr44jj2_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpe51u90u9.php:17\nStack trace:\n#0 /tmp/tmpe51u90u9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpe51u90u9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum = $sum + ($i*$i);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpnax2xoeb.php:17\nStack trace:\n#0 /tmp/tmpnax2xoeb.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpnax2xoeb.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6v2xdkkv.php:16\nStack trace:\n#0 /tmp/tmp6v2xdkkv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp6v2xdkkv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmj4n8p1q.php:16\nStack trace:\n#0 /tmp/tmpmj4n8p1q.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpmj4n8p1q.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpswj8xosu.php:17\nStack trace:\n#0 /tmp/tmpswj8xosu.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpswj8xosu.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpahb3amq2.php:17\nStack trace:\n#0 /tmp/tmpahb3amq2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpahb3amq2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpl94v8965.php:19\nStack trace:\n#0 /tmp/tmpl94v8965.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpl94v8965.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvoq_tuve.php:16\nStack trace:\n#0 /tmp/tmpvoq_tuve.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpvoq_tuve.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpe51u90u9.php:17\nStack trace:\n#0 /tmp/tmpe51u90u9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpe51u90u9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpipy2v4tf.php:17\nStack trace:\n#0 /tmp/tmpipy2v4tf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpipy2v4tf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwh2_25kd.php:16\nStack trace:\n#0 /tmp/tmpwh2_25kd.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpwh2_25kd.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp63nbauh9.php:16\nStack trace:\n#0 /tmp/tmp63nbauh9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp63nbauh9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps8jkht56.php:17\nStack trace:\n#0 /tmp/tmps8jkht56.php(22): test()\n#1 {main}\n  thrown in /tmp/tmps8jkht56.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpriea2ue2.php:17\nStack trace:\n#0 /tmp/tmpriea2ue2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpriea2ue2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpriea2ue2.php:17\nStack trace:\n#0 /tmp/tmpriea2ue2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpriea2ue2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqd_najyd.php:18\nStack trace:\n#0 /tmp/tmpqd_najyd.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqd_najyd.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppgkyydw9.php:17\nStack trace:\n#0 /tmp/tmppgkyydw9.php(22): test()\n#1 {main}\n  thrown in /tmp/tmppgkyydw9.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n\t$sum = 0;\n\tfor($i = 1; $i <= $n; $i++) {\n\t\t$sum = $sum + ($i * $i);\n\t}\n\treturn $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbeqgdoky.php:16\nStack trace:\n#0 /tmp/tmpbeqgdoky.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpbeqgdoky.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpap1yexn_.php:18\nStack trace:\n#0 /tmp/tmpap1yexn_.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpap1yexn_.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3ls96y3a.php:16\nStack trace:\n#0 /tmp/tmp3ls96y3a.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp3ls96y3a.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += pow($i, 2);\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp_cvht6ps.php:19\nStack trace:\n#0 /tmp/tmp_cvht6ps.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp_cvht6ps.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for ($i = 1; $i <= $n; $i++) {\n    $sum += $i * $i;\n  }\n  return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpl2tt6r21.php:17\nStack trace:\n#0 /tmp/tmpl2tt6r21.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpl2tt6r21.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps8jkht56.php:17\nStack trace:\n#0 /tmp/tmps8jkht56.php(22): test()\n#1 {main}\n  thrown in /tmp/tmps8jkht56.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpi7f5fgr9.php:16\nStack trace:\n#0 /tmp/tmpi7f5fgr9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpi7f5fgr9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum = $sum + $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpisyhl2_y.php:18\nStack trace:\n#0 /tmp/tmpisyhl2_y.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpisyhl2_y.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcp0v4wyo.php:19\nStack trace:\n#0 /tmp/tmpcp0v4wyo.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpcp0v4wyo.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow(2 * $i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "120",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqd_najyd.php:18\nStack trace:\n#0 /tmp/tmpqd_najyd.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqd_najyd.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpixxk70wh.php:18\nStack trace:\n#0 /tmp/tmpixxk70wh.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpixxk70wh.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpezz65c38.php:18\nStack trace:\n#0 /tmp/tmpezz65c38.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpezz65c38.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmppykycmcc.php:16\nStack trace:\n#0 /tmp/tmppykycmcc.php(21): test()\n#1 {main}\n  thrown in /tmp/tmppykycmcc.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpdodpqvv4.php:18\nStack trace:\n#0 /tmp/tmpdodpqvv4.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpdodpqvv4.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++){\n        if($i%2==0){\n            $sum += $i*$i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(6);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "56\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp0a7k4g0d.php:18\nStack trace:\n#0 /tmp/tmp0a7k4g0d.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp0a7k4g0d.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpi7f5fgr9.php:16\nStack trace:\n#0 /tmp/tmpi7f5fgr9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpi7f5fgr9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum = $sum + $i*$i;\n    }\n    return $sum;\n}\n$n = 5;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpp93_gy52.php:17\nStack trace:\n#0 /tmp/tmpp93_gy52.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpp93_gy52.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow(2*$i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum = $sum + ($i*$i);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptaji38p4.php:16\nStack trace:\n#0 /tmp/tmptaji38p4.php(21): test()\n#1 {main}\n  thrown in /tmp/tmptaji38p4.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpahb3amq2.php:17\nStack trace:\n#0 /tmp/tmpahb3amq2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpahb3amq2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8cmtsf2g.php:17\nStack trace:\n#0 /tmp/tmp8cmtsf2g.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp8cmtsf2g.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6v2xdkkv.php:16\nStack trace:\n#0 /tmp/tmp6v2xdkkv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp6v2xdkkv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\n$n = 5;\necho \"The sum of squares of first $n even natural numbers is \" . square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "The sum of squares of first 5 even natural numbers is 55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjat3gwkw.php:18\nStack trace:\n#0 /tmp/tmpjat3gwkw.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpjat3gwkw.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6v2xdkkv.php:16\nStack trace:\n#0 /tmp/tmp6v2xdkkv.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp6v2xdkkv.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpriea2ue2.php:17\nStack trace:\n#0 /tmp/tmpriea2ue2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpriea2ue2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpk3_l44u7.php:17\nStack trace:\n#0 /tmp/tmpk3_l44u7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpk3_l44u7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpl94v8965.php:19\nStack trace:\n#0 /tmp/tmpl94v8965.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpl94v8965.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpl94v8965.php:19\nStack trace:\n#0 /tmp/tmpl94v8965.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpl94v8965.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqd_najyd.php:18\nStack trace:\n#0 /tmp/tmpqd_najyd.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqd_najyd.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpijgaz_mn.php:16\nStack trace:\n#0 /tmp/tmpijgaz_mn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpijgaz_mn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for ($i = 0; $i <= $n; $i++) {\n    if ($i % 2 == 0) {\n      $sum += $i * $i;\n    }\n  }\n  return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvb9gycx7.php:18\nStack trace:\n#0 /tmp/tmpvb9gycx7.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpvb9gycx7.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptv4chd3w.php:17\nStack trace:\n#0 /tmp/tmptv4chd3w.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptv4chd3w.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxx2uewwg.php:17\nStack trace:\n#0 /tmp/tmpxx2uewwg.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpxx2uewwg.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\n$n = 4;\necho \"Sum of squares of first $n even natural numbers is: \" . square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "Sum of squares of first 4 even natural numbers is: 30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps7qkwt15.php:18\nStack trace:\n#0 /tmp/tmps7qkwt15.php(23): test()\n#1 {main}\n  thrown in /tmp/tmps7qkwt15.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n\t$sum = 0;\n\tfor ($i = 0; $i <= $n; $i++) {\n\t\tif ($i % 2 == 0) {\n\t\t\t$sum += $i * $i;\n\t\t}\n\t}\n\treturn $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmfkhv_7y.php:19\nStack trace:\n#0 /tmp/tmpmfkhv_7y.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpmfkhv_7y.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpk3_l44u7.php:17\nStack trace:\n#0 /tmp/tmpk3_l44u7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpk3_l44u7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbf9anypb.php:18\nStack trace:\n#0 /tmp/tmpbf9anypb.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpbf9anypb.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjlyo8he2.php:16\nStack trace:\n#0 /tmp/tmpjlyo8he2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjlyo8he2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=1; $i <= $n; $i++) { \n        if ($i%2 == 0) {\n            $sum += $i*$i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprz49bldx.php:18\nStack trace:\n#0 /tmp/tmprz49bldx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmprz49bldx.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpahb3amq2.php:17\nStack trace:\n#0 /tmp/tmpahb3amq2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpahb3amq2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\n$n = 5;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpc1q2xfjl.php:18\nStack trace:\n#0 /tmp/tmpc1q2xfjl.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpc1q2xfjl.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\n$n = 10;\necho \"Sum of squares of first $n even natural numbers is : \" . square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "Sum of squares of first 10 even natural numbers is : 385\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp242ilglc.php:18\nStack trace:\n#0 /tmp/tmp242ilglc.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp242ilglc.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=1; $i <= $n; $i++) { \n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpk5dmyxuc.php:20\nStack trace:\n#0 /tmp/tmpk5dmyxuc.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpk5dmyxuc.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9thdeg19.php:16\nStack trace:\n#0 /tmp/tmp9thdeg19.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp9thdeg19.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpgexalqp7.php:19\nStack trace:\n#0 /tmp/tmpgexalqp7.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpgexalqp7.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqd_najyd.php:18\nStack trace:\n#0 /tmp/tmpqd_najyd.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqd_najyd.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9thdeg19.php:16\nStack trace:\n#0 /tmp/tmp9thdeg19.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp9thdeg19.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpk3_l44u7.php:17\nStack trace:\n#0 /tmp/tmpk3_l44u7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpk3_l44u7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjlyo8he2.php:16\nStack trace:\n#0 /tmp/tmpjlyo8he2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpjlyo8he2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpahb3amq2.php:17\nStack trace:\n#0 /tmp/tmpahb3amq2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpahb3amq2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqd_najyd.php:18\nStack trace:\n#0 /tmp/tmpqd_najyd.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpqd_najyd.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvoq_tuve.php:16\nStack trace:\n#0 /tmp/tmpvoq_tuve.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpvoq_tuve.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpi7f5fgr9.php:16\nStack trace:\n#0 /tmp/tmpi7f5fgr9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpi7f5fgr9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1;$i<=$n;$i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp51hvcqx2.php:17\nStack trace:\n#0 /tmp/tmp51hvcqx2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp51hvcqx2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpp3gn1ytj.php:17\nStack trace:\n#0 /tmp/tmpp3gn1ytj.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpp3gn1ytj.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += pow($i, 2);\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp_cvht6ps.php:19\nStack trace:\n#0 /tmp/tmp_cvht6ps.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp_cvht6ps.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i < $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3eqrk1sf.php:17\nStack trace:\n#0 /tmp/tmp3eqrk1sf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp3eqrk1sf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum = $sum + ($i * $i);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcirlqvv3.php:17\nStack trace:\n#0 /tmp/tmpcirlqvv3.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpcirlqvv3.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 0; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8cmtsf2g.php:17\nStack trace:\n#0 /tmp/tmp8cmtsf2g.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp8cmtsf2g.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpruil6f9k.php:17\nStack trace:\n#0 /tmp/tmpruil6f9k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpruil6f9k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvoq_tuve.php:16\nStack trace:\n#0 /tmp/tmpvoq_tuve.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpvoq_tuve.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n  $sum = 0;\n  for($i = 1; $i <= $n; $i++) {\n    $sum += $i * $i;\n  }\n  return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpj_6ykfkj.php:17\nStack trace:\n#0 /tmp/tmpj_6ykfkj.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpj_6ykfkj.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "14\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpriea2ue2.php:17\nStack trace:\n#0 /tmp/tmpriea2ue2.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpriea2ue2.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpi7f5fgr9.php:16\nStack trace:\n#0 /tmp/tmpi7f5fgr9.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpi7f5fgr9.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpezz65c38.php:18\nStack trace:\n#0 /tmp/tmpezz65c38.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpezz65c38.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\n\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbcqgcvlf.php:17\nStack trace:\n#0 /tmp/tmpbcqgcvlf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpbcqgcvlf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5bge00x6.php:17\nStack trace:\n#0 /tmp/tmp5bge00x6.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp5bge00x6.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps8jkht56.php:17\nStack trace:\n#0 /tmp/tmps8jkht56.php(22): test()\n#1 {main}\n  thrown in /tmp/tmps8jkht56.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyyqd8siz.php:16\nStack trace:\n#0 /tmp/tmpyyqd8siz.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpyyqd8siz.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        if($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprrinxccl.php:19\nStack trace:\n#0 /tmp/tmprrinxccl.php(24): test()\n#1 {main}\n  thrown in /tmp/tmprrinxccl.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpch20lhx_.php:16\nStack trace:\n#0 /tmp/tmpch20lhx_.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpch20lhx_.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\n$n = 4;\necho square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp9wi525ie.php:18\nStack trace:\n#0 /tmp/tmp9wi525ie.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp9wi525ie.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 2; $i <= $n * 2; $i += 2) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(3);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "56",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2j_yj_o7.php:17\nStack trace:\n#0 /tmp/tmp2j_yj_o7.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp2j_yj_o7.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i = 1; $i <= $n; $i++) {\n        $sum += $i * $i;\n    }\n    return $sum;\n}\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvoq_tuve.php:16\nStack trace:\n#0 /tmp/tmpvoq_tuve.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpvoq_tuve.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 0; $i <= $n; $i++) {\n        $sum += pow($i, 2);\n    }\n    return $sum;\n}\n\necho square_Sum(4);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "30\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprur3mf78.php:17\nStack trace:\n#0 /tmp/tmprur3mf78.php(22): test()\n#1 {main}\n  thrown in /tmp/tmprur3mf78.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for($i=1; $i<=$n; $i++) {\n        $sum = $sum + ($i*$i);\n    }\n    return $sum;\n}\n\n$n = 5;\necho \"Sum of squares of first $n even natural numbers is: \" . square_Sum($n);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "Sum of squares of first 5 even natural numbers is: 55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7nxiiiz4.php:18\nStack trace:\n#0 /tmp/tmp7nxiiiz4.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp7nxiiiz4.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "20\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3on5z7vp.php:19\nStack trace:\n#0 /tmp/tmp3on5z7vp.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3on5z7vp.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i = 1; $i <= $n; $i++) {\n        if ($i % 2 == 0) {\n            $sum += $i * $i;\n        }\n    }\n    return $sum;\n}\n\necho square_Sum(10);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510437,
      "stdout": "220\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwm6bmnke.php:19\nStack trace:\n#0 /tmp/tmpwm6bmnke.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpwm6bmnke.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a phpthon function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfunction square_Sum($n) {\n    $sum = 0;\n    for ($i=1; $i <= $n; $i++) { \n        $sum += $i*$i;\n    }\n    return $sum;\n}\n\necho square_Sum(5);\nfunction candidate(...$args) {\n    return square_Sum(...$args);\n}\n\nfunction test(): void {\n    if (candidate(2) !== 20) { throw new Exception(\"Test failed!\"); }\n    if (candidate(3) !== 56) { throw new Exception(\"Test failed!\"); }\n    if (candidate(4) !== 120) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123549,
      "stdout": "55\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpy2qbrhnm.php:17\nStack trace:\n#0 /tmp/tmpy2qbrhnm.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpy2qbrhnm.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    }
  ]
}