{
  "name": "mbpp_268_find_star_num",
  "language": "rs",
  "prompt": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n",
  "doctests": "transform",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_268_find_star_num.py",
  "prompt_terminology": "reworded",
  "tests": "}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
  "stop_tokens": [
    "\n}"
  ],
  "results": [
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    let mut i = 1;\n    while count < n {\n        i += 1;\n        if is_star_num(i) {\n            star_num = i;\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp7l0qmfo3.rs:8:12\n  |\n8 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpkxat7g9c.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpps9853qr.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut counter = 1;\n    while counter < n {\n        star_num += 6 * counter;\n        counter += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpjg3vruvj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_nums = vec![1];\n\n    while star_nums.len() < n as usize {\n        i += 1;\n        let mut star_num = i * i;\n        let mut j = 1;\n        while star_num > 1 {\n            if star_nums.contains(&star_num) {\n                break;\n            }\n            star_num -= j;\n            j += 1;\n        }\n        if star_num == 1 {\n            star_nums.push(i * i);\n        }\n    }\n\n    star_nums[n as usize - 1]\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `16`,\n right: `37`', /tmp/tmpwn93i9_2.rs:27:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            i += 1;\n            if i == n {\n                return star_num;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpvixk5xme.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut n = n;\n    let mut star_num = 0;\n    let mut i = 1;\n    while n > 0 {\n        n -= i;\n        star_num += 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpc3zd9bqj.rs:16:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut star_count = 0;\n    let mut i = 1;\n    while star_count < n {\n        if is_star_num(i) {\n            star_num = i;\n            star_count += 1;\n        }\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpomfpsz5g.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut sum = 0;\n        while sum < star_num {\n            sum += j;\n            j += 1;\n        }\n        if sum == star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmp49vjcw8k.rs:22:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 2;\n        while j < star_num {\n            if star_num % j == 0 {\n                break;\n            }\n            j += 1;\n        }\n        if j == star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `37`', /tmp/tmp1qx9bpji.rs:23:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_num_count = 1;\n    let mut star_num_index = 1;\n    while star_num_count < n {\n        star_num_index += 1;\n        let mut star_num_index_copy = star_num_index;\n        let mut star_num_index_copy_count = 0;\n        while star_num_index_copy % star_num == 0 {\n            star_num_index_copy /= star_num;\n            star_num_index_copy_count += 1;\n        }\n        star_num_count *= star_num_index_copy_count + 1;\n        star_num += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        i += 1;\n        star_num = (star_num * 10) + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpjdkupo9p.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut n = n;\n    let mut star_num = 0;\n    let mut i = 1;\n    while n > 0 {\n        star_num += i;\n        i += 1;\n        n -= 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmph1kabmku.rs:16:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp36rg7kc8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpps9853qr.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j > 0 {\n            if is_star_num(j) {\n                i += 1;\n            }\n            j -= 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpd77gsqjz.rs:9:16\n  |\n9 |             if is_star_num(j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut count = 0;\n    while count < n {\n        i += 1;\n        if is_star_num(i) {\n            count += 1;\n        }\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0aje7wu8.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6 * count;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmptzivsu44.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6 * count;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmptzivsu44.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    let mut star_num_count = 1;\n    while star_count < n {\n        star_num += 1;\n        star_num_count = star_num_count * 10 + 1;\n        star_count += star_num_count;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpgny9z406.rs:16:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut num = star_num;\n        while num % j == 0 {\n            num /= j;\n            j += 1;\n        }\n        if num == 1 {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmp7ev9nx_5.rs:22:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut count = 0;\n    while count < n {\n        if is_star_num(i) {\n            count += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp5f3pm8eu.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmppey9l7gx.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 0;\n    let mut i = 1;\n    while num < n {\n        num += i;\n        i += 1;\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmppk8qmiyi.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmpdk6q7tr3.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        i += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpen9xx5nf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 0;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpuqwsn605.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        i += 1;\n        star_num = (star_num * 10) + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp_26wjdvo.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp8mis6cts.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % star_num == 0 {\n            j /= star_num;\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    while star_count < n {\n        star_num += 2;\n        star_count += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpcc5jguha.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    return i - 1;\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpfjtsfw3l.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 0;\n    while star_count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            star_count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp_doht2pu.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 1;\n    let mut count = 1;\n    while count < n {\n        num += 1;\n        if is_star_num(num) {\n            count += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpjigz9pvg.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut num = 0;\n    while i < n {\n        num += 1;\n        if is_star_num(num) {\n            i += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpzpqvehks.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % star_num == 0 {\n            j /= star_num;\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        let mut is_star_num = true;\n        while j > 1 {\n            if star_num % j != 0 {\n                is_star_num = false;\n                break;\n            }\n            j -= 1;\n        }\n        if is_star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcob4vk7e.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            if is_star_num(star_num + j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdr1h4_br.rs:9:16\n  |\n9 |             if is_star_num(star_num + j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    while star_count < n {\n        star_num += 2;\n        star_count += star_num * star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp2u2ngpo8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut count = 0;\n    while count < n {\n        i += 1;\n        if is_star_num(i) {\n            count += 1;\n        }\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0aje7wu8.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp7cqgb_38.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut result = 0;\n    let mut i = 0;\n    while i < n {\n        result += 1;\n        if is_star_num(result) {\n            i += 1;\n        }\n    }\n    result\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp_n51rc75.rs:7:12\n  |\n7 |         if is_star_num(result) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        let mut j = 1;\n        while j <= i {\n            star_num += 1;\n            if star_num == n {\n                return i;\n            }\n            j += 1;\n        }\n        i += 1;\n    }\n    0\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpzf2paic7.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut num = 1;\n    while star_num < n {\n        num += 1;\n        if is_star_num(num) {\n            star_num += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpyapz53f6.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            if is_prime(star_num + j) {\n                i += 1;\n                if i == n {\n                    return star_num;\n                }\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_prime` in this scope\n --> /tmp/tmp7sb7f20e.rs:9:16\n  |\n9 |             if is_prime(star_num + j) {\n  |                ^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpkxat7g9c.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut num = star_num;\n        while num % 2 == 0 {\n            j += 1;\n            num /= 2;\n        }\n        if j == star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num = star_num + i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpkyfsthut.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        let mut is_star_num = true;\n        while j > 1 {\n            if star_num % j == 0 {\n                is_star_num = false;\n                break;\n            }\n            j -= 1;\n        }\n        if is_star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 0;\n    while star_count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            star_count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp_doht2pu.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut sum = 0;\n        while j < star_num {\n            sum += j * j;\n            j += 1;\n        }\n        if sum == star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 2;\n        count += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp6gh5lp9j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpd26oy3iq.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp36rg7kc8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    while star_count < n {\n        star_num += 2;\n        star_count += star_num * star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp2u2ngpo8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6 * count;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmptzivsu44.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            if is_star_num(star_num, j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpp31f_92l.rs:9:16\n  |\n9 |             if is_star_num(star_num, j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num: isize = 0;\n    let mut i: isize = 1;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpdw0aornp.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut is_star_num = true;\n        while j * j <= star_num {\n            if star_num % j == 0 {\n                if j % 2 == 0 || (star_num / j) % 2 == 0 {\n                    is_star_num = false;\n                    break;\n                }\n            }\n            j += 1;\n        }\n        if is_star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `37`', /tmp/tmppsgliw0s.rs:27:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcob4vk7e.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut counter = 1;\n    while counter < n {\n        star_num += 6 * counter;\n        counter += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpjg3vruvj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp3_pnvace.rs:16:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut counter = 0;\n    let mut i = 0;\n    while counter < n {\n        i += 1;\n        let mut j = i;\n        let mut is_star_num = true;\n        while j > 0 {\n            if i % j == 0 {\n                if j != 1 && j != i {\n                    is_star_num = false;\n                    break;\n                }\n            }\n            j -= 1;\n        }\n        if is_star_num {\n            star_num = i;\n            counter += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmps6tz926o.rs:29:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 0;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpuqwsn605.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_nums = vec![1];\n    let mut i = 1;\n    while star_nums.len() < n as usize {\n        let mut num = star_nums[i - 1];\n        while num % 2 == 0 {\n            num /= 2;\n        }\n        while num % 5 == 0 {\n            num /= 5;\n        }\n        star_nums.push(num);\n        i += 1;\n    }\n    star_nums[n as usize - 1]\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `1`,\n right: `37`', /tmp/tmpuoa9tva9.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % 2 == 0 {\n            j /= 2;\n        }\n        while j % 3 == 0 {\n            j /= 3;\n        }\n        while j % 5 == 0 {\n            j /= 5;\n        }\n        if j == 1 {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpqdsmy8ib.rs:26:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmpoys6e7o0.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpd26oy3iq.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % 10 == 9 {\n            j /= 10;\n        }\n        if j % 10 == 1 {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp58rnw3av.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        let mut j = 1;\n        while j <= i {\n            star_num += 1;\n            if star_num == n {\n                return i;\n            }\n            j += 1;\n        }\n        i += 1;\n    }\n    0\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpzf2paic7.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp65xh06h8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_nums = vec![1];\n    while star_nums.len() < n as usize {\n        let mut j = 1;\n        let mut star_num = 0;\n        while j <= i {\n            star_num += star_nums[j as usize - 1] * star_nums[(i - j) as usize];\n            j += 1;\n        }\n        star_nums.push(star_num);\n        i += 1;\n    }\n    star_nums[n as usize - 1]\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpygto_f5a.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpkxat7g9c.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut count = 0;\n    while count < n {\n        if is_star_num(i) {\n            count += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp5f3pm8eu.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_star_num(star_num + j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpk0yc_8e7.rs:9:16\n  |\n9 |             if is_star_num(star_num + j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut count = 0;\n    while count < n {\n        i += 1;\n        if is_star_num(i) {\n            count += 1;\n        }\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0aje7wu8.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut is_star_num = true;\n        while j * j <= star_num {\n            if star_num % j == 0 {\n                is_star_num = !is_star_num;\n            }\n            j += 1;\n        }\n        if is_star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `8`,\n right: `37`', /tmp/tmpndvikypj.rs:24:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        i += 1;\n        star_num = (star_num * 10) + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpjdkupo9p.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        i += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpen9xx5nf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpd26oy3iq.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp70xu_r9t.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcob4vk7e.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpkxat7g9c.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if star_num % j == 0 {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpicq90hpw.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp8mis6cts.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    while star_count < n {\n        star_num += 2;\n        star_count += star_num * star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp2u2ngpo8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        i += 1;\n        star_num += 6 * (i - 1);\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpvycpuqmh.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    return star_num;\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp6ql6lray.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            i += 1;\n            if i == n {\n                return star_num;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpek_pelz9.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num = i * (i + 1) * (i + 2) / 6;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `4`,\n right: `37`', /tmp/tmp6qq1jv0a.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut count = 0;\n    let mut star_num = 0;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpzoaa2hwm.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_prime(star_num + j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_prime` in this scope\n --> /tmp/tmprdz4lf0c.rs:9:16\n  |\n9 |             if is_prime(star_num + j) {\n  |                ^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_prime(star_num + j) {\n                i += 1;\n                if i == n {\n                    return star_num;\n                }\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_prime` in this scope\n --> /tmp/tmpg1avp901.rs:9:16\n  |\n9 |             if is_prime(star_num + j) {\n  |                ^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    while star_count < n {\n        star_num += 2;\n        star_count += star_num * star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp2u2ngpo8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcob4vk7e.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp3blwzx74.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        i += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpen9xx5nf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    }
  ]
}