{
  "name": "mbpp_287_square_Sum",
  "language": "rs",
  "prompt": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n",
  "doctests": "keep",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_287_square_Sum.py",
  "prompt_terminology": "verbatim",
  "tests": "}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
  "stop_tokens": [
    "\n}"
  ],
  "results": [
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        if i % 2 == 0 {\n            sum += i * i;\n        }\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `4`,\n right: `20`', /tmp/tmp0hm9cx4_.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n {\n        if i % 2 == 0 {\n            sum += i * i;\n        }\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `0`,\n right: `20`', /tmp/tmpzeamri5z.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp_9xme5__.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp_9xme5__.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum: isize = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp9_d0100f.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum: isize = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp1a6vqxv0.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp_9xme5__.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp_9xme5__.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpfttglnel.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpc473ninb.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..(n+1) {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpm7bgbzj0.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n {\n        if i % 2 == 0 {\n            sum += i * i;\n        }\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `0`,\n right: `20`', /tmp/tmpzeamri5z.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpfttglnel.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..(n + 1) {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp16mb5s8q.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp_9xme5__.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp_9xme5__.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 0..n {\n        sum += (2 * i + 2).pow(2);\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum: isize = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp1a6vqxv0.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..=n {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp7r4cy6td.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp4cmaneq4.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpu3lgd6g_.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n + 1 {\n        sum += i * i;\n    }\n    sum\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1665510377,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmpj9jyu860.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a python function takes in an integer n and returns the sum of squares of first n even natural numbers.\nfn square_Sum(n: isize) -> isize {\n    let mut sum = 0;\n    for i in 1..n+1 {\n        sum += i*i;\n    }\n    return sum;\n}\n\nfn main() {\n    let candidate = square_Sum;\n    assert_eq!(candidate(2), 20);\n    assert_eq!(candidate(3), 56);\n    assert_eq!(candidate(4), 120);\n}\n",
      "timestamp": 1666123548,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `20`', /tmp/tmp0evdpuly.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    }
  ]
}