{
  "name": "mbpp_268_find_star_num",
  "language": "rs",
  "prompt": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n",
  "doctests": "keep",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_268_find_star_num.py",
  "prompt_terminology": "verbatim",
  "tests": "}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
  "stop_tokens": [
    "\n}"
  ],
  "results": [
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        let mut j = 1;\n        while j <= i {\n            star_num += 1;\n            if star_num == n {\n                return i;\n            }\n            j += 1;\n        }\n        i += 1;\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpz7is_b7r.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpi96hya1v.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            if is_star_num(star_num * star_num + j * j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpyeoj5qss.rs:9:16\n  |\n9 |             if is_star_num(star_num * star_num + j * j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num = find_star_num_for_i(i);\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `find_star_num_for_i` in this scope\n --> /tmp/tmpqa4tbgsy.rs:6:20\n  |\n6 |         star_num = find_star_num_for_i(i);\n  |                    ^^^^^^^^^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            if is_star_num(star_num * star_num + j * j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp_8x55z0x.rs:9:16\n  |\n9 |             if is_star_num(star_num * star_num + j * j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if star_num % j == 0 {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmp3gobtd9e.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num + 1;\n        while j < star_num * 2 {\n            if is_star_num(j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpz2erkqrz.rs:9:16\n  |\n9 |             if is_star_num(j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 1;\n    let mut count = 0;\n    while count < n {\n        num += 1;\n        if is_star_num(num) {\n            count += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpuki35ngq.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpgsyk4gcs.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpkp4nq07j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpveetk50q.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if star_num % j == 0 {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmp3gobtd9e.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        i += 1;\n        star_num = (star_num * 10) + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpjdkupo9p.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `15`,\n right: `37`', /tmp/tmpr6326zq5.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 2;\n        count += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp6gh5lp9j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num * 2 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `7`,\n right: `37`', /tmp/tmp1iw6w3vi.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpkxat7g9c.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % 2 == 0 {\n            j /= 2;\n        }\n        while j % 3 == 0 {\n            j /= 3;\n        }\n        while j % 5 == 0 {\n            j /= 5;\n        }\n        if j == 1 {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpf4hbnxdj.rs:26:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp_btwyurb.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 0;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpuqwsn605.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % star_num == 0 {\n            j /= star_num;\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (i * (i + 1)) / 2;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmp2si3iti0.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpi96hya1v.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        i += 1;\n        if is_star_num(i) {\n            star_num += 1;\n        }\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpx3qth7wg.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_prime(star_num + j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_prime` in this scope\n --> /tmp/tmprdz4lf0c.rs:9:16\n  |\n9 |             if is_prime(star_num + j) {\n  |                ^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmppey9l7gx.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut num = 0;\n    while i < n {\n        num += 1;\n        if is_star_num(num) {\n            i += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpzpqvehks.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6 * count;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmptzivsu44.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_star_num(star_num * star_num + j * j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpc1lz_0lu.rs:9:16\n  |\n9 |             if is_star_num(star_num * star_num + j * j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmphpypejss.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpi96hya1v.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num + 1;\n        while j < star_num * star_num {\n            if is_star_num(j) {\n                i += 1;\n                if i == n {\n                    return j;\n                }\n            }\n            j += 1;\n        }\n    }\n    0\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpw7j1fug0.rs:9:16\n  |\n9 |             if is_star_num(j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    if n < 1 {\n        return 0;\n    }\n    let mut star_num = 0;\n    let mut i = 1;\n    while i <= n {\n        star_num = i * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmpyh_456dz.rs:17:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpi96hya1v.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp65xh06h8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % 2 == 0 {\n            j /= 2;\n        }\n        while j % 3 == 0 {\n            j /= 3;\n        }\n        while j % 5 == 0 {\n            j /= 5;\n        }\n        if j == 1 {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpf4hbnxdj.rs:26:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_prime(star_num + j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_prime` in this scope\n --> /tmp/tmprdz4lf0c.rs:9:16\n  |\n9 |             if is_prime(star_num + j) {\n  |                ^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        i += 1;\n        if is_star_num(i) {\n            star_num += 1;\n        }\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpx3qth7wg.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = star_num + i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpz_xqun4h.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num * 10) + 9;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpkxat7g9c.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % star_num == 0 {\n            i += 1;\n            j /= star_num;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123882,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut curr = 1;\n    let mut count = 0;\n    while count < n {\n        curr += 1;\n        if is_star_num(curr) {\n            count += 1;\n        }\n    }\n    curr\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpege2j2pb.rs:7:12\n  |\n7 |         if is_star_num(curr) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    if n == 1 {\n        return 1;\n    }\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpx0hztchh.rs:17:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_star_num(star_num * j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp877paid7.rs:9:16\n  |\n9 |             if is_star_num(star_num * j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp65xh06h8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 0;\n    while star_count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            star_count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp_doht2pu.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 0;\n    while count < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123870,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpuqwsn605.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp3kcdcgqc.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j <= star_num {\n            if is_star_num(star_num * j) {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp35l2sazx.rs:9:16\n  |\n9 |             if is_star_num(star_num * j) {\n  |                ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpi96hya1v.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num: isize = 0;\n    let mut i: isize = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    return i - 1;\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdg3boq32.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        while j < star_num {\n            if star_num % j == 0 {\n                i += 1;\n            }\n            j += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `4`,\n right: `37`', /tmp/tmp28ko2c67.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 0;\n    let mut count = 0;\n    while count < n {\n        num += 1;\n        if is_star_num(num) {\n            count += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpnb3q7rey.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `1111`,\n right: `37`', /tmp/tmpwp1v50th.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 0;\n    let mut i = 1;\n    while num < n {\n        i += 1;\n        if is_star_num(i) {\n            num += 1;\n        }\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0ypqxsvh.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 1;\n    let mut count = 0;\n    while count < n {\n        num += 1;\n        if is_star_num(num) {\n            count += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpuki35ngq.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut count = 0;\n    let mut i = 1;\n    while count < n {\n        if is_star_num(i) {\n            count += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp1_sx4ve5.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp36rg7kc8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut num = 0;\n    while i < n {\n        num += 1;\n        if is_star_num(num) {\n            i += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpzpqvehks.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num: isize = 1;\n    let mut i: isize = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp11aizlx4.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut sum = 0;\n        while sum < star_num {\n            sum += j;\n            j += 1;\n        }\n        if sum == star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmps1azqo3m.rs:23:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpi96hya1v.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp65xh06h8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        i += 1;\n        star_num = (star_num * 10) + 9;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `999`,\n right: `37`', /tmp/tmpbq_gelyx.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpq2eg_juu.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num = star_num + i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpkyfsthut.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        let mut j = 1;\n        while j <= i {\n            star_num += 1;\n            if star_num == n {\n                return i;\n            }\n            j += 1;\n        }\n        i += 1;\n    }\n    0\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpzf2paic7.rs:21:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut j = 1;\n    let mut k = 1;\n    while k < n {\n        i = j;\n        j = j + 1;\n        k = k + 1;\n        while j % i == 0 {\n            j = j + 1;\n            k = k + 1;\n        }\n    }\n    j\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123883,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        i += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpen9xx5nf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 0;\n    while count < n {\n        let mut num = star_num;\n        let mut sum = 0;\n        while num > 0 {\n            sum += num % 10;\n            num /= 10;\n        }\n        if sum == 10 {\n            count += 1;\n        }\n        star_num += 1;\n    }\n    star_num - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `46`,\n right: `73`', /tmp/tmpih_p6sn2.rs:23:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpcvrysm4o.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        i += 1;\n        star_num = (star_num * 10) + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp_26wjdvo.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    for i in 1..n + 1 {\n        star_num += i;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmphu9qo3it.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp8mis6cts.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmp8mis6cts.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 1;\n    let mut count = 1;\n    while count < n {\n        num += 2;\n        let mut i = 1;\n        while i * i <= num {\n            if num % i == 0 {\n                count += 1;\n            }\n            i += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `5`,\n right: `37`', /tmp/tmpigjlsc3f.rs:20:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut j = 1;\n    let mut k = 1;\n    while k < n {\n        i = j;\n        j = j + 2;\n        k = k + 1;\n    }\n    i\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp8l8y6dvi.rs:16:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `6`,\n right: `37`', /tmp/tmpaw5t5mlm.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % 2 == 0 {\n            j /= 2;\n        }\n        while j % 3 == 0 {\n            j /= 3;\n        }\n        while j % 5 == 0 {\n            j /= 5;\n        }\n        if j == 1 {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpf4hbnxdj.rs:26:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 6 * count;\n        count += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmptzivsu44.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    while count < n {\n        star_num += 2;\n        count += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp6gh5lp9j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num = i * (i + 1) / 2;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmppdsdoj9e.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut num = 0;\n    while i < n {\n        num += 1;\n        if is_star_num(num) {\n            i += 1;\n        }\n    }\n    num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpzpqvehks.rs:7:12\n  |\n7 |         if is_star_num(num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 4;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `9`,\n right: `37`', /tmp/tmprzbou27w.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut num = 0;\n    let mut i = 1;\n    while num < n {\n        if is_star_num(i) {\n            num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpzplj1sb6.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmp4wy93ahf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_num_count = 0;\n    let mut i = 1;\n    while star_num_count < n {\n        if is_star_num(i) {\n            star_num = i;\n            star_num_count += 1;\n        }\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpqak1u7nw.rs:7:12\n  |\n7 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = star_num * 10 + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp65xh06h8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut count = 1;\n    let mut i = 1;\n    while count < n {\n        i += 1;\n        if is_star_num(i) {\n            star_num = i;\n            count += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp7l0qmfo3.rs:8:12\n  |\n8 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        i += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpen9xx5nf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        i += star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `2`,\n right: `37`', /tmp/tmpen9xx5nf.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 0;\n    while i <= n {\n        star_num = (star_num + i) * 2;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123878,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `22`,\n right: `37`', /tmp/tmp7fhkv2u2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    for i in 1..n {\n        star_num = (star_num * 10) + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123878,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpt3pisyf4.rs:12:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut i = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123877,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmp3kcdcgqc.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    if n == 1 {\n        return 1;\n    }\n\n    let mut star_num = 1;\n    let mut i = 2;\n    while i <= n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123878,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpk1md6vvn.rs:19:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        if is_star_num(i) {\n            star_num += 1;\n        }\n        i += 1;\n    }\n    i - 1\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510671,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmp0pwmgfkg.rs:6:12\n  |\n6 |         if is_star_num(i) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num = star_num + i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmpkyfsthut.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 0;\n    let mut i = 1;\n    while star_num < n {\n        star_num += i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp16434gu2.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % star_num == 0 {\n            i += 1;\n            j /= star_num;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123882,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = star_num;\n        while j % star_num == 0 {\n            j /= star_num;\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123876,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = star_num + 4 * i;\n        i = i + 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `13`,\n right: `37`', /tmp/tmpn3dvffcj.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        if is_star_num(star_num) {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "error[E0425]: cannot find function `is_star_num` in this scope\n --> /tmp/tmpdlwpnuth.rs:7:12\n  |\n7 |         if is_star_num(star_num) {\n  |            ^^^^^^^^^^^ not found in this scope\n\nerror: aborting due to previous error\n\nFor more information about this error, try `rustc --explain E0425`.\n",
      "exit_code": 1,
      "status": "SyntaxError"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut star_num = 1;\n    let mut star_count = 1;\n    while star_count < n {\n        star_num += 2;\n        star_count += star_num * star_num;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123871,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `3`,\n right: `37`', /tmp/tmp2u2ngpo8.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num += 6 * i;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `19`,\n right: `37`', /tmp/tmpb8m7bk4j.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 0;\n    let mut star_num = 0;\n    while i < n {\n        star_num += 1;\n        let mut j = 1;\n        let mut is_star_num = true;\n        while j < star_num {\n            if star_num % j == 0 {\n                is_star_num = false;\n                break;\n            }\n            j += 1;\n        }\n        if is_star_num {\n            i += 1;\n        }\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1666123883,
      "stdout": "",
      "stderr": "",
      "exit_code": -1,
      "status": "Timeout"
    },
    {
      "program": "/// Write a function to find the n'th star number.\nfn find_star_num(n: isize) -> isize {\n    let mut i = 1;\n    let mut star_num = 1;\n    while i < n {\n        star_num = (star_num * 10) + 1;\n        i += 1;\n    }\n    star_num\n}\n\nfn main() {\n    let candidate = find_star_num;\n    assert_eq!(candidate(3), 37);\n    assert_eq!(candidate(4), 73);\n    assert_eq!(candidate(5), 121);\n}\n",
      "timestamp": 1665510672,
      "stdout": "",
      "stderr": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `111`,\n right: `37`', /tmp/tmpveetk50q.rs:14:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n",
      "exit_code": 101,
      "status": "Exception"
    }
  ]
}