###################### python3 prepare_prompts_yaml.py --lang humaneval_to_sh.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-sh --target-dir ../experiments/sh-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in translate_expr
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in <listcomp>
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 30, in translate_expr
    return translator.gen_list([translate_expr(translator, e) for e in elts])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_sh.py", line 202, in gen_list
    raise Exception("Cannot translate list element that contains whitespace")
Exception: Cannot translate list element that contains whitespace
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluati
Exception translating expressions for HumanEval_29_filter_by_prefix.py: Cannot translate list element that contains whitespace
Exception translating prompt for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_7_filter_by_substring.py: Cannot translate list element that contains whitespace

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_sh.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-sh --target-dir ../experiments/sh-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in translate_expr
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in <listcomp>
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 30, in translate_expr
    return translator.gen_list([translate_expr(translator, e) for e in elts])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_sh.py", line 202, in gen_list
    raise Exception("Cannot translate list element that contains whitespace")
Exception: Cannot translate list element that contains whitespace
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluati
Exception translating expressions for HumanEval_29_filter_by_prefix.py: Cannot translate list element that contains whitespace
Exception translating prompt for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_7_filter_by_substring.py: Cannot translate list element that contains whitespace

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_sh.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-sh --target-dir ../experiments/sh-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in translate_expr
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in <listcomp>
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 30, in translate_expr
    return translator.gen_list([translate_expr(translator, e) for e in elts])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_sh.py", line 202, in gen_list
    raise Exception("Cannot translate list element that contains whitespace")
Exception: Cannot translate list element that contains whitespace
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluati
Exception translating expressions for HumanEval_29_filter_by_prefix.py: Cannot translate list element that contains whitespace
Exception translating prompt for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_7_filter_by_substring.py: Cannot translate list element that contains whitespace

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_sh.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-sh --target-dir ../experiments/sh-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in translate_expr
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 41, in <listcomp>
    [translate_expr(translator, a) for a in args],
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 30, in translate_expr
    return translator.gen_list([translate_expr(translator, e) for e in elts])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_sh.py", line 202, in gen_list
    raise Exception("Cannot translate list element that contains whitespace")
Exception: Cannot translate list element that contains whitespace
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluati
Exception translating expressions for HumanEval_29_filter_by_prefix.py: Cannot translate list element that contains whitespace
Exception translating prompt for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_113_odd_count.py: Cannot translate list element that contains whitespace
Exception translating expressions for HumanEval_7_filter_by_substring.py: Cannot translate list element that contains whitespace

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_cpp.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-cpp --target-dir ../experiments/cpp-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' ob
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no attribu
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_cpp.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-cpp --target-dir ../experiments/cpp-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' ob
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no attribu
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_cpp.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-cpp --target-dir ../experiments/cpp-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' ob
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no attribu
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_cpp.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-cpp --target-dir ../experiments/cpp-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_cpp.py", line 396, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' ob
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no attribu
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_d.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-d --target-dir ../experiments/d-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_d.py", line 176, in gen_call
    for value, type_name in zip(args, self.func_type):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in tra
Exception translating prompt for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_151_double_the_difference.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_151_double_the_difference.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_143_words_in_sentence.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_143_words_in_sentence.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_92_any_int.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_92_any_int.py: 'NoneType' object is not iterable
Exception tra
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_d.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-d --target-dir ../experiments/d-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_d.py", line 176, in gen_call
    for value, type_name in zip(args, self.func_type):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in tra
Exception translating prompt for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_137_compare_one.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_137_compare_one.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_22_filter_integers.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_22_filter_integers.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_103_rounded_avg.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_103_rounded_avg.py: 'NoneType' object is not iterable
Exception translating prompt 
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_d.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-d --target-dir ../experiments/d-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_d.py", line 176, in gen_call
    for value, type_name in zip(args, self.func_type):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in tra
Exception translating prompt for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_137_compare_one.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_137_compare_one.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_22_filter_integers.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_22_filter_integers.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_103_rounded_avg.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_103_rounded_avg.py: 'NoneType' object is not iterable
Exception translating prompt 
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_d.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-d --target-dir ../experiments/d-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_d.py", line 176, in gen_call
    for value, type_name in zip(args, self.func_type):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in tra
Exception translating prompt for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_24_largest_divisor.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_47_median.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_137_compare_one.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_137_compare_one.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_22_filter_integers.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_22_filter_integers.py: 'NoneType' object is not iterable
Exception translating prompt for HumanEval_103_rounded_avg.py: 'NoneType' object is not iterable
Exception translating expressions for HumanEval_103_rounded_avg.py: 'NoneType' object is not iterable
Exception translating prompt 
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_go.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-go --target-dir ../experiments/go-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in gen_call
    args = [self.patch_empty(arg, self.type[0][i])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in <listcomp>
    args = [self.patch_empty(arg, self.type[0][i])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
Exception translating prompt for HumanEval_24_largest_divisor.py: list index out of range
Exception translating expressions for HumanEval_24_largest_divisor.py: list index out of range
Exception translating prompt for HumanEval_47_median.py: list index out of range
Exception translating expressions for HumanEval_47_median.py: list index out of range
Exception translating prompt for HumanEval_11_string_xor.py: list index out of range
Exception translating expressions for HumanEval_11_string_xor.py: list index out of range
Exception translating prompt for HumanEval_60_sum_to_n.py: list index out of range
Exception translating expressions for HumanEval_60_sum_to_n.py: list index out of range
Exception translating prompt for HumanEval_151_double_the_difference.py: list index out of range
empty list. needs patching
Exception translating expressions for HumanEval_151_double_the_difference.py: list index out of range
Exception translating prompt for HumanEval_23_strlen.py: list index out of range
Exception translati
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_go.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-go --target-dir ../experiments/go-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in gen_call
    args = [self.patch_empty(arg, self.type[0][i])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in <listcomp>
    args = [self.patch_empty(arg, self.type[0][i])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
Exception translating prompt for HumanEval_24_largest_divisor.py: list index out of range
Exception translating expressions for HumanEval_24_largest_divisor.py: list index out of range
Exception translating prompt for HumanEval_47_median.py: list index out of range
Exception translating expressions for HumanEval_47_median.py: list index out of range
Exception translating prompt for HumanEval_11_string_xor.py: list index out of range
Exception translating expressions for HumanEval_11_string_xor.py: list index out of range
Exception translating prompt for HumanEval_144_simplify.py: list index out of range
Exception translating expressions for HumanEval_144_simplify.py: list index out of range
Exception translating prompt for HumanEval_115_max_fill.py: list index out of range
Exception translating expressions for HumanEval_115_max_fill.py: list index out of range
Exception translating prompt for HumanEval_120_maximum.py: list index out of range
Exception translating expressions for HumanEval_120_maximum.py: list
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_go.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-go --target-dir ../experiments/go-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in gen_call
    args = [self.patch_empty(arg, self.type[0][i])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in <listcomp>
    args = [self.patch_empty(arg, self.type[0][i])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
Exception translating prompt for HumanEval_24_largest_divisor.py: list index out of range
Exception translating expressions for HumanEval_24_largest_divisor.py: list index out of range
Exception translating prompt for HumanEval_47_median.py: list index out of range
Exception translating expressions for HumanEval_47_median.py: list index out of range
Exception translating prompt for HumanEval_11_string_xor.py: list index out of range
Exception translating expressions for HumanEval_11_string_xor.py: list index out of range
Exception translating prompt for HumanEval_144_simplify.py: list index out of range
Exception translating expressions for HumanEval_144_simplify.py: list index out of range
Exception translating prompt for HumanEval_115_max_fill.py: list index out of range
Exception translating expressions for HumanEval_115_max_fill.py: list index out of range
Exception translating prompt for HumanEval_120_maximum.py: list index out of range
Exception translating expressions for HumanEval_120_maximum.py: list
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_go.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-go --target-dir ../experiments/go-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in gen_call
    args = [self.patch_empty(arg, self.type[0][i])
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_go.py", line 308, in <listcomp>
    args = [self.patch_empty(arg, self.type[0][i])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
Exception translating prompt for HumanEval_24_largest_divisor.py: list index out of range
Exception translating expressions for HumanEval_24_largest_divisor.py: list index out of range
Exception translating prompt for HumanEval_47_median.py: list index out of range
Exception translating expressions for HumanEval_47_median.py: list index out of range
Exception translating prompt for HumanEval_11_string_xor.py: list index out of range
Exception translating expressions for HumanEval_11_string_xor.py: list index out of range
Exception translating prompt for HumanEval_144_simplify.py: list index out of range
Exception translating expressions for HumanEval_144_simplify.py: list index out of range
Exception translating prompt for HumanEval_115_max_fill.py: list index out of range
Exception translating expressions for HumanEval_115_max_fill.py: list index out of range
Exception translating prompt for HumanEval_120_maximum.py: list index out of range
Exception translating expressions for HumanEval_120_maximum.py: list
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_java.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-java --target-dir ../experiments/java-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' 
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_java.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-java --target-dir ../experiments/java-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' 
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_135_can_arrange.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_31_is_prime.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_104_unique_digits.py: can only concatenate str (not "tuple") to str
Excepti
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_java.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-java --target-dir ../experiments/java-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' 
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_135_can_arrange.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_31_is_prime.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_104_unique_digits.py: can only concatenate str (not "tuple") to str
Excepti
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_java.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-java --target-dir ../experiments/java-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_java.py", line 262, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator' 
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_135_can_arrange.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_31_is_prime.py: can only concatenate str (not "tuple") to str
Exception translating prompt for HumanEval_104_unique_digits.py: can only concatenate str (not "tuple") to str
Excepti
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_rs.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-rs --target-dir ../experiments/rs-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in gen_call
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in <listcomp>
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 114, in coerce
    return f"Vec::<{translate_type(to)}>::new()"
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 96, in translate_type
    raise Exception("explicitly untyped argument")
Exception: explicitly untyped argument

Union unsupported
explicitly untyped argument
Exception translating expressions for HumanEval_22_filter_integers.py: explicitly untyped argument
Union unsupported
no ellipsis!!
Union unsupported

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_rs.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-rs --target-dir ../experiments/rs-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in gen_call
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in <listcomp>
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 114, in coerce
    return f"Vec::<{translate_type(to)}>::new()"
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 96, in translate_type
    raise Exception("explicitly untyped argument")
Exception: explicitly untyped argument

Union unsupported
explicitly untyped argument
Exception translating expressions for HumanEval_22_filter_integers.py: explicitly untyped argument
Union unsupported
no ellipsis!!
Union unsupported

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_rs.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-rs --target-dir ../experiments/rs-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in gen_call
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in <listcomp>
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 114, in coerce
    return f"Vec::<{translate_type(to)}>::new()"
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 96, in translate_type
    raise Exception("explicitly untyped argument")
Exception: explicitly untyped argument

Union unsupported
explicitly untyped argument
Exception translating expressions for HumanEval_22_filter_integers.py: explicitly untyped argument
Union unsupported
no ellipsis!!
Union unsupported

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_rs.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-rs --target-dir ../experiments/rs-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 178, in translate_tests
    left = translate_expr(translator, left)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in gen_call
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 252, in <listcomp>
    args = [coerce(arg, self.type[0][i]) for i, arg in enumerate(args)]
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 114, in coerce
    return f"Vec::<{translate_type(to)}>::new()"
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_rs.py", line 96, in translate_type
    raise Exception("explicitly untyped argument")
Exception: explicitly untyped argument

Union unsupported
explicitly untyped argument
Exception translating expressions for HumanEval_22_filter_integers.py: explicitly untyped argument
Union unsupported
no ellipsis!!
Union unsupported

###################### python3 prepare_prompts_yaml.py --lang humaneval_to_scala.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-scala --target-dir ../experiments/scala-davinci-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_scala.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-scala --target-dir ../experiments/scala-davinci-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_scala.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-scala --target-dir ../experiments/scala-incoder-0.2-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no
###################### python3 prepare_prompts_yaml.py --lang humaneval_to_scala.py --doctests transform --originals ../datasets/originals-with-cleaned-vocab-scala --target-dir ../experiments/scala-incoder-0.8-reworded
Traceback (most recent call last):
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 146, in translate_prompt
    return prompt_visitor.translate_func_decl(doctest_transformation)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 105, in translate_func_decl
    transl_funccall = translate_expr(self.translator, funcCall)
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/generic_translator.py", line 39, in translate_expr
    return translator.gen_call(
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in gen_call
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
  File "/home/arjun/repos/polyglot-codegen-evaluation/src/humaneval_to_scala.py", line 264, in <listcomp>
    return func_name + "(" + ", ".join([self.update_type(args[i], self.args_type[i]) for i in range(len(args))]) + ")", None
AttributeError: 'Translator
Exception translating prompt for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_24_largest_divisor.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_47_median.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_47_median.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_35_max_element.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_35_max_element.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'args_type'
Exception translating expressions for HumanEval_135_can_arrange.py: 'Translator' object has no attribute 'entry_point'
Exception translating prompt for HumanEval_134_check_if_last_char_is_a_letter.py: 'Translator' object has no
